[package]
version = "1.2.1.0"
name = "Wakunguma.Folio-Budgetingapp"
display-name = "Folio - Budgeting app"
publisher = "CN=70A3CBD3-185D-4DDE-9F41-27073B2FE013"
publisher-name = "Wakunguma Kalimukwa"
logo="icons/icon.png"
resources = ["build/**/*","icons/**/*"]

[application]
id = "Folio"
executable = "folio.exe"
description = "A free, privacy focused budgeting app."
display-name = "Folio"